kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: fast
provisioner: kubernetes.io/vsphere-volume
parameters:
  datastore: LUN01
  diskformat: thin
  fstype: ext3 
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mssql-data
  annotations:
    volume.beta.kubernetes.io/storage-class: fast
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
